apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "jenkinstest-ingress"
  annotations:
    ingress.kubernetes.io/rewrite-target: /,
    ingress.kubernetes.io/secure-backends: true
spec:
  rules:
  - http:
      paths:
      - path: /jenkinstest
        backend:
          serviceName: jenkinstest-service
          servicePort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: "jenkinstest-service"
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  # the port that this service should serve on
  - name: https
    port: 9443

  selector:
    app: "jenkinstest-selector"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "jenkinstest-deployment"
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: "jenkinstest-selector"
    spec:
      containers:
      - name: jenkinstest
        image: dc1cp01.icp:8500/jenkinstest/<DOCKER_IMAGE>
        readinessProbe:
          httpGet:
            path: /jenkinstest/health
            port: 9080
          initialDelaySeconds: 60
      nodeSelector:
        beta.kubernetes.io/arch: s390x
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
